// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1286: (x0,x1) => x0.createElement(x1),
      _1292: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1293: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1293(f,arguments.length,x0,x1,x2) }),
      _1294: (x0,x1) => x0.append(x1),
      _1296: x0 => x0.remove(),
      _1297: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _1298: (x0,x1) => x0.removeAttribute(x1),
      _1300: (x0,x1) => x0.getResponseHeader(x1),
      _1323: (x0,x1) => x0.item(x1),
      _1326: (x0,x1) => { x0.csp = x1 },
      _1327: x0 => x0.csp,
      _1328: (x0,x1) => x0.getCookieExpirationDate(x1),
      _1330: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1331: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1332: (x0,x1) => x0.createElement(x1),
      _1337: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1348: x0 => x0.toArray(),
      _1349: x0 => x0.toUint8Array(),
      _1350: x0 => ({serverTimestamps: x0}),
      _1351: x0 => ({source: x0}),
      _1354: x0 => new firebase_firestore.FieldPath(x0),
      _1355: (x0,x1) => new firebase_firestore.FieldPath(x0,x1),
      _1356: (x0,x1,x2) => new firebase_firestore.FieldPath(x0,x1,x2),
      _1357: (x0,x1,x2,x3) => new firebase_firestore.FieldPath(x0,x1,x2,x3),
      _1358: (x0,x1,x2,x3,x4) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4),
      _1359: (x0,x1,x2,x3,x4,x5) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5),
      _1360: (x0,x1,x2,x3,x4,x5,x6) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6),
      _1361: (x0,x1,x2,x3,x4,x5,x6,x7) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6,x7),
      _1362: (x0,x1,x2,x3,x4,x5,x6,x7,x8) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6,x7,x8),
      _1363: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6,x7,x8,x9),
      _1364: () => globalThis.firebase_firestore.documentId(),
      _1365: (x0,x1) => new firebase_firestore.GeoPoint(x0,x1),
      _1366: x0 => globalThis.firebase_firestore.vector(x0),
      _1367: x0 => globalThis.firebase_firestore.Bytes.fromUint8Array(x0),
      _1369: (x0,x1) => globalThis.firebase_firestore.collection(x0,x1),
      _1371: (x0,x1) => globalThis.firebase_firestore.doc(x0,x1),
      _1374: x0 => x0.call(),
      _1406: (x0,x1) => ({includeMetadataChanges: x0,source: x1}),
      _1407: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1407(f,arguments.length,x0) }),
      _1408: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1408(f,arguments.length,x0) }),
      _1409: (x0,x1,x2,x3) => globalThis.firebase_firestore.onSnapshot(x0,x1,x2,x3),
      _1410: (x0,x1,x2) => globalThis.firebase_firestore.onSnapshot(x0,x1,x2),
      _1412: (x0,x1) => globalThis.firebase_firestore.setDoc(x0,x1),
      _1413: (x0,x1) => globalThis.firebase_firestore.query(x0,x1),
      _1414: x0 => globalThis.firebase_firestore.getDocs(x0),
      _1415: x0 => globalThis.firebase_firestore.getDocsFromServer(x0),
      _1416: x0 => globalThis.firebase_firestore.getDocsFromCache(x0),
      _1417: x0 => globalThis.firebase_firestore.limit(x0),
      _1418: x0 => globalThis.firebase_firestore.limitToLast(x0),
      _1419: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1419(f,arguments.length,x0) }),
      _1420: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1420(f,arguments.length,x0) }),
      _1421: (x0,x1) => globalThis.firebase_firestore.orderBy(x0,x1),
      _1423: (x0,x1,x2) => globalThis.firebase_firestore.where(x0,x1,x2),
      _1425: x0 => globalThis.firebase_firestore.doc(x0),
      _1428: (x0,x1) => x0.data(x1),
      _1432: x0 => x0.docChanges(),
      _1450: (x0,x1) => globalThis.firebase_firestore.getFirestore(x0,x1),
      _1452: x0 => globalThis.firebase_firestore.Timestamp.fromMillis(x0),
      _1453: (module,f) => finalizeWrapper(f, function() { return module.exports._1453(f,arguments.length) }),
      _1585: () => globalThis.firebase_firestore.updateDoc,
      _1586: () => globalThis.firebase_firestore.or,
      _1587: () => globalThis.firebase_firestore.and,
      _1601: x0 => x0.path,
      _1604: () => globalThis.firebase_firestore.GeoPoint,
      _1605: x0 => x0.latitude,
      _1606: x0 => x0.longitude,
      _1608: () => globalThis.firebase_firestore.VectorValue,
      _1609: () => globalThis.firebase_firestore.Bytes,
      _1612: x0 => x0.type,
      _1614: x0 => x0.doc,
      _1616: x0 => x0.oldIndex,
      _1618: x0 => x0.newIndex,
      _1620: () => globalThis.firebase_firestore.DocumentReference,
      _1624: x0 => x0.path,
      _1633: x0 => x0.metadata,
      _1634: x0 => x0.ref,
      _1639: x0 => x0.docs,
      _1641: x0 => x0.metadata,
      _1646: () => globalThis.firebase_firestore.Timestamp,
      _1647: x0 => x0.seconds,
      _1648: x0 => x0.nanoseconds,
      _1684: x0 => x0.hasPendingWrites,
      _1686: x0 => x0.fromCache,
      _1693: x0 => x0.source,
      _1698: () => globalThis.firebase_firestore.startAfter,
      _1699: () => globalThis.firebase_firestore.startAt,
      _1700: () => globalThis.firebase_firestore.endBefore,
      _1701: () => globalThis.firebase_firestore.endAt,
      _1728: x0 => x0.decode(),
      _1729: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1730: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1731: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1731(f,arguments.length,x0) }),
      _1732: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1732(f,arguments.length,x0) }),
      _1733: x0 => x0.send(),
      _1734: () => new XMLHttpRequest(),
      _1745: x0 => x0.reload(),
      _1752: (x0,x1) => globalThis.firebase_auth.updateProfile(x0,x1),
      _1755: x0 => x0.toJSON(),
      _1756: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1756(f,arguments.length,x0) }),
      _1757: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1757(f,arguments.length,x0) }),
      _1758: (x0,x1,x2) => x0.onAuthStateChanged(x1,x2),
      _1759: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1759(f,arguments.length,x0) }),
      _1760: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1760(f,arguments.length,x0) }),
      _1761: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1761(f,arguments.length,x0) }),
      _1762: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1762(f,arguments.length,x0) }),
      _1763: (x0,x1,x2) => x0.onIdTokenChanged(x1,x2),
      _1767: (x0,x1,x2) => globalThis.firebase_auth.createUserWithEmailAndPassword(x0,x1,x2),
      _1773: (x0,x1,x2) => globalThis.firebase_auth.sendPasswordResetEmail(x0,x1,x2),
      _1777: (x0,x1,x2) => globalThis.firebase_auth.signInWithEmailAndPassword(x0,x1,x2),
      _1782: x0 => x0.signOut(),
      _1783: (x0,x1) => globalThis.firebase_auth.connectAuthEmulator(x0,x1),
      _1806: x0 => globalThis.firebase_auth.OAuthProvider.credentialFromResult(x0),
      _1821: x0 => globalThis.firebase_auth.getAdditionalUserInfo(x0),
      _1822: (x0,x1,x2) => ({errorMap: x0,persistence: x1,popupRedirectResolver: x2}),
      _1823: (x0,x1) => globalThis.firebase_auth.initializeAuth(x0,x1),
      _1829: x0 => globalThis.firebase_auth.OAuthProvider.credentialFromError(x0),
      _1832: (x0,x1) => ({displayName: x0,photoURL: x1}),
      _1844: () => globalThis.firebase_auth.debugErrorMap,
      _1847: () => globalThis.firebase_auth.browserSessionPersistence,
      _1849: () => globalThis.firebase_auth.browserLocalPersistence,
      _1851: () => globalThis.firebase_auth.indexedDBLocalPersistence,
      _1854: x0 => globalThis.firebase_auth.multiFactor(x0),
      _1855: (x0,x1) => globalThis.firebase_auth.getMultiFactorResolver(x0,x1),
      _1857: x0 => x0.currentUser,
      _1861: x0 => x0.tenantId,
      _1871: x0 => x0.displayName,
      _1872: x0 => x0.email,
      _1873: x0 => x0.phoneNumber,
      _1874: x0 => x0.photoURL,
      _1875: x0 => x0.providerId,
      _1876: x0 => x0.uid,
      _1877: x0 => x0.emailVerified,
      _1878: x0 => x0.isAnonymous,
      _1879: x0 => x0.providerData,
      _1880: x0 => x0.refreshToken,
      _1881: x0 => x0.tenantId,
      _1882: x0 => x0.metadata,
      _1884: x0 => x0.providerId,
      _1885: x0 => x0.signInMethod,
      _1886: x0 => x0.accessToken,
      _1887: x0 => x0.idToken,
      _1888: x0 => x0.secret,
      _1900: x0 => x0.creationTime,
      _1901: x0 => x0.lastSignInTime,
      _1906: x0 => x0.code,
      _1908: x0 => x0.message,
      _1920: x0 => x0.email,
      _1921: x0 => x0.phoneNumber,
      _1922: x0 => x0.tenantId,
      _1945: x0 => x0.user,
      _1948: x0 => x0.providerId,
      _1949: x0 => x0.profile,
      _1950: x0 => x0.username,
      _1951: x0 => x0.isNewUser,
      _1954: () => globalThis.firebase_auth.browserPopupRedirectResolver,
      _1959: x0 => x0.displayName,
      _1960: x0 => x0.enrollmentTime,
      _1961: x0 => x0.factorId,
      _1962: x0 => x0.uid,
      _1964: x0 => x0.hints,
      _1965: x0 => x0.session,
      _1967: x0 => x0.phoneNumber,
      _1977: x0 => ({displayName: x0}),
      _1978: x0 => ({photoURL: x0}),
      _1979: (x0,x1) => x0.getItem(x1),
      _1984: (x0,x1) => x0.appendChild(x1),
      _1987: (x0,x1,x2,x3,x4,x5,x6,x7) => ({apiKey: x0,authDomain: x1,databaseURL: x2,projectId: x3,storageBucket: x4,messagingSenderId: x5,measurementId: x6,appId: x7}),
      _1988: (x0,x1) => globalThis.firebase_core.initializeApp(x0,x1),
      _1989: x0 => globalThis.firebase_core.getApp(x0),
      _1990: () => globalThis.firebase_core.getApp(),
      _1991: (x0,x1,x2) => globalThis.firebase_core.registerVersion(x0,x1,x2),
      _1993: () => globalThis.firebase_core.SDK_VERSION,
      _1999: x0 => x0.apiKey,
      _2001: x0 => x0.authDomain,
      _2003: x0 => x0.databaseURL,
      _2005: x0 => x0.projectId,
      _2007: x0 => x0.storageBucket,
      _2009: x0 => x0.messagingSenderId,
      _2011: x0 => x0.measurementId,
      _2013: x0 => x0.appId,
      _2015: x0 => x0.name,
      _2016: x0 => x0.options,
      _2017: (x0,x1,x2) => x0.setItem(x1,x2),
      _2018: (x0,x1) => x0.debug(x1),
      _2019: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2019(f,arguments.length,x0) }),
      _2020: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._2020(f,arguments.length,x0,x1) }),
      _2021: (x0,x1) => ({createScript: x0,createScriptURL: x1}),
      _2022: (x0,x1,x2) => x0.createPolicy(x1,x2),
      _2023: (x0,x1) => x0.createScriptURL(x1),
      _2024: (x0,x1,x2) => x0.createScript(x1,x2),
      _2025: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2025(f,arguments.length,x0) }),
      _2027: Date.now,
      _2029: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _2030: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _2031: () => new Error().stack,
      _2032: () => typeof dartUseDateNowForTicks !== "undefined",
      _2033: () => 1000 * performance.now(),
      _2034: () => Date.now(),
      _2035: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _2036: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _2037: () => new WeakMap(),
      _2038: (map, o) => map.get(o),
      _2039: (map, o, v) => map.set(o, v),
      _2040: (exn) => exn.toString(),
      _2041: (exn) => exn.stack,
      _2042: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _2043: x0 => new WeakRef(x0),
      _2044: x0 => x0.deref(),
      _2051: () => globalThis.WeakRef,
      _2054: s => JSON.stringify(s),
      _2055: s => printToConsole(s),
      _2056: (o, p, r) => o.replaceAll(p, () => r),
      _2057: (o, p, r) => o.replace(p, () => r),
      _2058: Function.prototype.call.bind(String.prototype.toLowerCase),
      _2059: s => s.toUpperCase(),
      _2060: s => s.trim(),
      _2061: s => s.trimLeft(),
      _2062: s => s.trimRight(),
      _2063: (string, times) => string.repeat(times),
      _2064: Function.prototype.call.bind(String.prototype.indexOf),
      _2065: (s, p, i) => s.lastIndexOf(p, i),
      _2066: (string, token) => string.split(token),
      _2067: Object.is,
      _2071: (o, c) => o instanceof c,
      _2072: o => Object.keys(o),
      _2074: (o,s,v) => o[s] = v,
      _2102: x0 => new Array(x0),
      _2104: x0 => x0.length,
      _2106: (x0,x1) => x0[x1],
      _2107: (x0,x1,x2) => { x0[x1] = x2 },
      _2110: (x0,x1,x2) => new DataView(x0,x1,x2),
      _2112: x0 => new Int8Array(x0),
      _2113: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _2115: x0 => new Uint8ClampedArray(x0),
      _2117: x0 => new Int16Array(x0),
      _2119: x0 => new Uint16Array(x0),
      _2121: x0 => new Int32Array(x0),
      _2123: x0 => new Uint32Array(x0),
      _2125: x0 => new Float32Array(x0),
      _2127: x0 => new Float64Array(x0),
      _2147: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._2147(f,arguments.length,x0,x1) }),
      _2150: () => Symbol("jsBoxedDartObjectProperty"),
      _2151: x0 => x0.random(),
      _2154: () => globalThis.Math,
      _2167: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _2168: (handle) => clearTimeout(handle),
      _2169: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _2170: (handle) => clearInterval(handle),
      _2171: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _2172: () => Date.now(),
      _2173: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _2174: (x0,x1) => x0.exec(x1),
      _2175: (x0,x1) => x0.test(x1),
      _2176: x0 => x0.pop(),
      _2178: o => o === undefined,
      _2180: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _2182: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _2183: o => o instanceof RegExp,
      _2184: (l, r) => l === r,
      _2185: o => o,
      _2186: o => o,
      _2187: o => o,
      _2188: b => !!b,
      _2189: o => o.length,
      _2191: (o, i) => o[i],
      _2192: f => f.dartFunction,
      _2193: () => ({}),
      _2194: () => [],
      _2196: () => globalThis,
      _2197: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _2199: (o, p) => o[p],
      _2200: (o, p, v) => o[p] = v,
      _2201: (o, m, a) => o[m].apply(o, a),
      _2203: o => String(o),
      _2204: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _2205: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2205(f,arguments.length,x0) }),
      _2206: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._2206(f,arguments.length,x0,x1) }),
      _2207: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _2208: o => [o],
      _2209: (o0, o1) => [o0, o1],
      _2210: (o0, o1, o2) => [o0, o1, o2],
      _2211: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _2212: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2213: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2216: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2217: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2218: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2219: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2220: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2221: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2222: x0 => new ArrayBuffer(x0),
      _2223: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _2225: x0 => x0.index,
      _2227: x0 => x0.flags,
      _2228: x0 => x0.multiline,
      _2229: x0 => x0.ignoreCase,
      _2230: x0 => x0.unicode,
      _2231: x0 => x0.dotAll,
      _2232: (x0,x1) => { x0.lastIndex = x1 },
      _2233: (o, p) => p in o,
      _2234: (o, p) => o[p],
      _2235: (o, p, v) => o[p] = v,
      _2236: (o, p) => delete o[p],
      _2237: () => new XMLHttpRequest(),
      _2238: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _2240: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _2241: (x0,x1) => x0.send(x1),
      _2242: x0 => x0.send(),
      _2245: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2245(f,arguments.length,x0) }),
      _2246: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2246(f,arguments.length,x0) }),
      _2251: (x0,x1,x2) => x0.open(x1,x2),
      _2252: x0 => x0.abort(),
      _2253: x0 => x0.getAllResponseHeaders(),
      _2254: () => new AbortController(),
      _2255: x0 => x0.abort(),
      _2256: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _2257: (x0,x1) => globalThis.fetch(x0,x1),
      _2258: (x0,x1) => x0.get(x1),
      _2259: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._2259(f,arguments.length,x0,x1,x2) }),
      _2260: (x0,x1) => x0.forEach(x1),
      _2261: x0 => x0.getReader(),
      _2262: x0 => x0.cancel(),
      _2263: x0 => x0.read(),
      _2270: () => globalThis.window.flutter_inappwebview,
      _2274: (x0,x1) => { x0.nativeCommunication = x1 },
      _2275: x0 => x0.trustedTypes,
      _2276: (x0,x1) => { x0.text = x1 },
      _2277: o => o instanceof Array,
      _2282: a => a.pop(),
      _2283: (a, i) => a.splice(i, 1),
      _2284: (a, s) => a.join(s),
      _2285: (a, s, e) => a.slice(s, e),
      _2287: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _2288: a => a.length,
      _2290: (a, i) => a[i],
      _2291: (a, i, v) => a[i] = v,
      _2293: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _2294: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _2296: o => o instanceof Uint8Array,
      _2297: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _2298: o => o instanceof Int8Array,
      _2299: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _2300: o => o instanceof Uint8ClampedArray,
      _2301: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _2302: o => o instanceof Uint16Array,
      _2303: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _2304: o => o instanceof Int16Array,
      _2305: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _2306: o => o instanceof Uint32Array,
      _2307: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _2308: o => o instanceof Int32Array,
      _2309: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _2311: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _2312: o => o instanceof Float32Array,
      _2313: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _2314: o => o instanceof Float64Array,
      _2315: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _2316: (t, s) => t.set(s),
      _2318: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _2320: o => o.buffer,
      _2321: o => o.byteOffset,
      _2322: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _2323: (b, o) => new DataView(b, o),
      _2324: (b, o, l) => new DataView(b, o, l),
      _2325: Function.prototype.call.bind(DataView.prototype.getUint8),
      _2326: Function.prototype.call.bind(DataView.prototype.setUint8),
      _2327: Function.prototype.call.bind(DataView.prototype.getInt8),
      _2328: Function.prototype.call.bind(DataView.prototype.setInt8),
      _2329: Function.prototype.call.bind(DataView.prototype.getUint16),
      _2330: Function.prototype.call.bind(DataView.prototype.setUint16),
      _2331: Function.prototype.call.bind(DataView.prototype.getInt16),
      _2332: Function.prototype.call.bind(DataView.prototype.setInt16),
      _2333: Function.prototype.call.bind(DataView.prototype.getUint32),
      _2334: Function.prototype.call.bind(DataView.prototype.setUint32),
      _2335: Function.prototype.call.bind(DataView.prototype.getInt32),
      _2336: Function.prototype.call.bind(DataView.prototype.setInt32),
      _2339: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _2340: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _2341: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _2342: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _2343: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _2344: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _2345: Function.prototype.call.bind(Number.prototype.toString),
      _2346: Function.prototype.call.bind(BigInt.prototype.toString),
      _2347: Function.prototype.call.bind(Number.prototype.toString),
      _2348: (d, digits) => d.toFixed(digits),
      _2360: () => globalThis.document,
      _2366: (x0,x1) => { x0.height = x1 },
      _2368: (x0,x1) => { x0.width = x1 },
      _2370: (x0,x1) => { x0.pointerEvents = x1 },
      _2379: x0 => x0.style,
      _2382: x0 => x0.src,
      _2383: (x0,x1) => { x0.src = x1 },
      _2384: x0 => x0.naturalWidth,
      _2385: x0 => x0.naturalHeight,
      _2401: x0 => x0.status,
      _2402: (x0,x1) => { x0.responseType = x1 },
      _2404: x0 => x0.response,
      _2441: x0 => x0.readyState,
      _2443: (x0,x1) => { x0.timeout = x1 },
      _2445: (x0,x1) => { x0.withCredentials = x1 },
      _2446: x0 => x0.upload,
      _2447: x0 => x0.responseURL,
      _2448: x0 => x0.status,
      _2449: x0 => x0.statusText,
      _2451: (x0,x1) => { x0.responseType = x1 },
      _2452: x0 => x0.response,
      _2453: x0 => x0.responseText,
      _2464: x0 => x0.loaded,
      _2465: x0 => x0.total,
      _2529: x0 => x0.style,
      _3005: x0 => x0.src,
      _3006: (x0,x1) => { x0.src = x1 },
      _3009: x0 => x0.name,
      _3010: (x0,x1) => { x0.name = x1 },
      _3011: x0 => x0.sandbox,
      _3012: x0 => x0.allow,
      _3013: (x0,x1) => { x0.allow = x1 },
      _3014: x0 => x0.allowFullscreen,
      _3015: (x0,x1) => { x0.allowFullscreen = x1 },
      _3020: x0 => x0.referrerPolicy,
      _3021: (x0,x1) => { x0.referrerPolicy = x1 },
      _3768: (x0,x1) => { x0.type = x1 },
      _3776: (x0,x1) => { x0.crossOrigin = x1 },
      _3778: (x0,x1) => { x0.text = x1 },
      _4235: () => globalThis.window,
      _4278: x0 => x0.location,
      _4297: x0 => x0.navigator,
      _4559: x0 => x0.trustedTypes,
      _4560: x0 => x0.sessionStorage,
      _4576: x0 => x0.hostname,
      _4686: x0 => x0.userAgent,
      _6841: x0 => x0.signal,
      _6915: () => globalThis.document,
      _6996: x0 => x0.body,
      _6998: x0 => x0.head,
      _7327: x0 => x0.id,
      _7328: (x0,x1) => { x0.id = x1 },
      _7558: x0 => x0.length,
      _8673: x0 => x0.value,
      _8675: x0 => x0.done,
      _9377: x0 => x0.url,
      _9379: x0 => x0.status,
      _9381: x0 => x0.statusText,
      _9382: x0 => x0.headers,
      _9383: x0 => x0.body,
      _11511: (x0,x1) => { x0.border = x1 },
      _11789: (x0,x1) => { x0.display = x1 },
      _11953: (x0,x1) => { x0.height = x1 },
      _12643: (x0,x1) => { x0.width = x1 },
      _13011: x0 => x0.name,
      _13729: () => globalThis.console,
      _13757: x0 => x0.name,
      _13758: x0 => x0.message,
      _13759: x0 => x0.code,
      _13761: x0 => x0.customData,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
